### ISSUE TITLE
Add D4C to our cloud testing flow

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#1197]
## Summary
As part of D4C migration to cloud security team, we want to add D4C integration pre-installed to our cloud deployment workflow

### Definition of done
- [ ] Add Defend for containers integration to our cloud deployment workflow

**Comment by gurevichdmitry** [comment]
@oren-zohar The default Kubernetes version for EKS, as it was when our terraform code was initially created, has always been 1.24 and has not changed according to our GitHub repo history. Our Live Track Environment, including EKS clusters provisioned through Terraform, is operating on this 1.24 version. However, it's important to note that our functional testing for EKS is conducted on version 1.23, and the vanilla Kubernetes environment is running on version 1.23.12.

<img width="966" alt="Screenshot 2023-08-10 at 9 02 50" src="https://github.com/elastic/cloudbeat/assets/99176494/cd660f6e-767e-4a68-8daf-ed2b1453ae71">

Regarding the potential for errors or missing rules evaluation, it's important to note that version 1.24 should not introduce new issues. We are aware that the significant change related to PodSecurityPolicy (PSP) deprecation is expected to start with Kubernetes version 1.25. Therefore, the move to version 1.24 for our integration should not directly trigger PSP-related challenges. The transition to 1.25, which brings substantial changes in this regard, is the milestone where we need to pay close attention to PSP adjustments and ensure our integration is prepared for the upcoming changes. Since the recent QA cycles have been carried out on EKS 1.24, and our live track environment is also aligned with this version, there shouldn't be any immediate concerns affecting our current setup.

Additionally, it's worth mentioning that [Amazon's EKS documentation](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html) indicates the end of support for EKS cluster v1.23 on October 11, 2023. 

<img width="1112" alt="Screenshot 2023-08-10 at 8 59 57" src="https://github.com/elastic/cloudbeat/assets/99176494/2a6f9009-eae0-4ab5-ae4b-96336222e5a2">

This means that we won't be able to provision new clusters using Terraform or other tools, and our EKS cluster used for functional testing will be updated automatically.

<img width="1062" alt="Screenshot 2023-08-10 at 9 01 29" src="https://github.com/elastic/cloudbeat/assets/99176494/2255e219-c3fc-4bdc-b115-86042a70f49f">


Considering the information above, I still recommend moving forward with the initial proposal to share an EKS cluster running version 1.24 for both the KSPM and D4C integrations, hosted on the same agent. This approach ensures compatibility, aligns with our current environment, and prepares us for the upcoming changes in Kubernetes versions.

**Comment by gurevichdmitry** [comment]
Check out my [Kibana environment](https://p.elstc.co/paste/acVmyiP7#F8h0cKLPJzGk38UCFyshkyOwL0eOLcatAwM66GWcKfm) for details on the installed integrations.

**Comment by gurevichdmitry** [comment]
@eyalkraft, We're using the same elastic agent for both KSPM EKS and D4C, deployed as a daemon set with the **cloudbeat** and **cloud_defend** binaries running as separate processes. The Kubernetes manifest is mostly identical for both integrations, with the only difference being the need to uncomment the capabilities section for D4C integration.
