### ISSUE TITLE
[CIS Azure] Manual credentials flow

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1278]
**Motivation**
Besides assuming a role we would like to also have a manual credentials flow.
In order to do it we need to pass the credentials via the integration (Kibana UI).
Here is an issue to perform the assignment in the integration:
- https://github.com/elastic/cloudbeat/issues/1277

In addition to that we also need to support this in `cloudbeat` as well.
I have an initial PR that supports role assignment and I've already added the fields to the configuration.
- https://github.com/elastic/cloudbeat/pull/1275/files#diff-fe44f09c4d5977b5f5eaea29170b6a0748819c9d02271746a20d81a5f3efca17
- https://github.com/elastic/cloudbeat/pull/1275/files#diff-8fd78f686eecd6652219a0e862286d11d873ce3f25d420f265907ceef57b12daR67

Filling up these stubs and testing that flow should be sufficient.

**Definition of done**
What needs to be completed at the end of this task
- [ ] We want to support custom credentials without assuming a role 

**Out of scope**
What should not be included in this task

**Related tasks/epics**
Reference related issues and epics

**Comment by moukoublen** [comment]
Notes: Currently the azure sdk provides these credentials options:

| Name    |  Description |
| -------- | ------- |
| AzureCLICredential         | This credential doesn't cache tokens, so every call invokes the CLI. :x: |
| DefaultAzureCredential     | is a default credential chain for applications that will deploy to Azure. It attempts to authenticate with each of these credential types, in the following order: (EnvironmentCredential, WorkloadIdentityCredential, ManagedIdentityCredential, AzureCLICredential) |
| ClientAssertionCredential  | authenticates an application with assertions provided by a callback function (This credential is for advanced scenarios) |
| ClientCertificateCredential| authenticates a service principal with a certificate |
| ClientSecretCredential     | authenticates an application with a client secret (string) |
| DeviceCodeCredential       | acquires tokens for a user via the device code flow, which has the user browse to an Azure Active Directory URL, enter a code, and authenticate. :x: |
| EnvironmentCredential      | authenticates a service principal with a secret or certificate, or a user with a password, depending on environment variable configuration. :x: |
| ManagedIdentityCredential  | authenticates an Azure managed identity in any hosting environment supporting managed identities. This credential authenticates a system-assigned identity by default. Use ManagedIdentityCredentialOptions.ID to specify a user-assigned identity. See Azure Active Directory [documentation](https://docs.microsoft.com/azure/active-directory/managed-identities-azure-resources/overview) for more information about managed identities. Go SDK [link](https://learn.microsoft.com/en-us/azure/developer/go/azure-sdk-authentication-managed-identity?tabs=azure-cli) |
| OnBehalfOfCredential       | authenticates a service principal via the on-behalf-of flow. This is typically used by middle-tier services that authorize requests to other services with a delegated user identity. Because this is not an interactive authentication flow, an application using it must have admin consent for any delegated permissions before requesting tokens for them. See [Azure Active Directory documentation] for more details.|
| UsernamePasswordCredential | authenticates a user with a password. Microsoft doesn't recommend this kind of authentication because it's less secure than other authentication flows. This credential is not interactive, so it isn't compatible with any form of multi-factor authentication, and the application must already have user or admin consent. This credential can only authenticate work and school accounts; it can't authenticate Microsoft accounts. |



https://learn.microsoft.com/en-us/azure/developer/go/azure-sdk-authentication-service-principal?tabs=azure-cli

**Comment by orestisfl** [comment]
> This credential doesn't cache tokens, so every call invokes the CLI. ❌

Amazing :exploding_head:

**Comment by maxcold** [comment]
will be tested with 
- https://github.com/elastic/kibana/issues/165579
