### ISSUE TITLE
`bump-golang` pipeline is broken

### ISSUE THREAD

**Issue by orestisfl** [elastic/cloudbeat#1377]
**Describe the bug**
Quite straightforward ticket, the `bump-goland` pipeline is broken: https://github.com/elastic/cloudbeat/actions/workflows/bump-golang.yml. This ticket is about 1. finding the reason behind the failure 2. fixing the problem 3. making sure the pipeline works and updates go to the latest version

**Comment by orestisfl** [comment]
CC @v1v

**Comment by v1v** [comment]
hey, you can test those changes locally if you follow the below steps:

1) Install https://www.updatecli.io/docs/prologue/installation/
2) if you use `gh cli` then

```bash
GITHUB_TOKEN=$(gh auth token) \
  GIT_USER=foo \
  GIT_EMAIL=bar \
  updatecli apply --config .ci/bump-golang.yml --push=false
```

Then you will there is some weird error when detecting the minor version, and it seems https://github.com/elastic/cloudbeat/pull/671/files#diff-69c69535f549f1e70ce037415e46a2894f04d4147c7929de6ef1db8f72a0a136R1 moved from 3 digits version to 2 digits version and the relevant changes in the `updatecli` pipeline were not populated.


If you change the `.ci/bump-golang.yml` to detect the minor version using the 2 digits format:

```diff
diff --git a/.ci/bump-golang.yml b/.ci/bump-golang.yml
index e9d9d61..ecbde7f 100644
--- a/.ci/bump-golang.yml
+++ b/.ci/bump-golang.yml
@@ -31,7 +31,7 @@ sources:
     kind: shell
     transformers:
       - findsubmatch:
-          pattern: '^\d+.(\d+).\d+$'
+          pattern: '^\d+.(\d+)$'
           captureindex: 1
     spec:
       command: cat .go-version
(END)
```

then you will see it moves forward but it also fails:

```
✗ Bump golang-version to latest version:
	Source:
		✔ [gomod] Get version in go.mod format
		✔ [latestGoVersion] Get Latest Go Release
		✔ [minor] Get minor version in .go-version
	Condition:
		✔ [dockerTag] Is docker image golang:1.20.8 published
		✔ [goDefaultVersion-check] Check if defined golang version differs
	Target:
		✗ [update-go-version] Update .go-version 1.20.8
		✔ [update-gomod] Update go.mod 1.20
		✗ [update-version.asciidoc] Update version.asciidoc 1.20.8

```


The question is:

- Does 3 digits golang version is required? 

Otherwise, I don't think `bump-golang` is required. Though, there are certain issues while using `2 digits` versions rather than `3 digits` versions - such as breaking changes will be happening in `main` rather than being detected on a PR with the bump. I don't know what's the direction the cloudbeat wanna move forward
