### ISSUE TITLE
[GCP] Investigate why deployments can't be deleted

### ISSUE THREAD

**Issue by orouz** [elastic/cloudbeat#1384]
**Motivation**

trying to manually remove a deployment from the gcp cloud console results in an error:
<img width="867" alt="Screenshot 2023-10-03 at 14 55 32" src="https://github.com/elastic/cloudbeat/assets/20814186/ad73f9c0-b7bd-40b3-83b0-8fc33145c607">

**Definition of done**
- figure out why this happens for an org owner role. 
- make sure deployments can be removed

**Out of scope**

**Related tasks/epics**

**Comment by orouz** [comment]
turns out this is addressed in our [docs](https://www.elastic.co/guide/en/security/current/cspm-get-started-gcp.html#:~:text=During%20Cloud%20Shell,Role%20Administrator.)

this happens for `8.10`, but not `8.11`. we may want to backport our deployment manager script to `8.10`? @uri-weisman @oren-zohar

**Comment by uri-weisman** [comment]
@oren-zohar just to provide more context - In 8.11 we made a few improvements to the onboarding script, such as:
1. Transitioning to GCP's built-in roles instead of utilizing a custom role, which previously necessitated the addition of extra permissions to the default service account.
2. Implementing the removal of these additional permissions only when they were not previously present.
