### ISSUE TITLE
[BUG] Cloudbeat cluster leader election not working

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#145]
**Describe the bug**
When deploying a three-node kind cluster, I've noticed that all of the three cloudbeat instances are sending Kubernetes findings and fetching data.

**Preconditions**
Three-node kind cluster.

**To Reproduce**
1. Deploy a three-node kind cluster.
2. Deploy elastic agent with cloudbeat daemonset.
3. Go to cloud posture -> findings -> filter k8s_object.
4. Look at the agent that is sending the findings and you will see that you are getting them from all instances.

**Expected behavior**
Only the leader instance should send the findings for k8s_object resources.

**Screenshots**
<img width="1074" alt="Screen Shot 2022-05-15 at 12 27 58" src="https://user-images.githubusercontent.com/12246907/168466277-529e3f99-6db5-40c7-860a-54c2103f8072.png">
<img width="1450" alt="Screen Shot 2022-05-15 at 12 30 24" src="https://user-images.githubusercontent.com/12246907/168466282-ffb56ad9-6b9e-4b77-975a-153954845389.png">

**Comment by kfirpeled** [comment]
@jeniawhite, can you say if this happens when there's more than one master?
On our system flows we haven't defined a cluster to check it, worth adding a dedicated test for this one.

**Comment by eyalkraft** [comment]
@kfirpeled leader election lease and k8s master node are unrelated.

The reason this bug is effecting the user is the decision we made to include `node id` in the resource id of kube-api resources. If we would have used only their uuid or their uuid combined with the cluster id all the collected findings for the same resources would have been squashed into a single latest finding per resource (per rule).

@amitkanfer This raises another concern for the case of the leader changing. All our kube-resource ids would change as a result (since the node Id used in their resource id is the id of the node where the leader agent was running on). Since we keep stale findings for a while this will result with a spike in resource number and then a decrease back to the real number.

Generally seems a bit problematic to have the resource Id of some Pod change based on who fetched the pod's info (this is not even related to where the pod is running but where the agent is running.

**Comment by tehilashn** [comment]
This sounds very similar to https://github.com/elastic/security-team/issues/4125 although the outcome is that all the agents are sending k8s objects. When working on https://github.com/elastic/security-team/issues/4125 let's verify that it is indeed the same.

**Comment by uri-weisman** [comment]
FIxed by:
- https://github.com/elastic/cloudbeat/pull/295

**Comment by ofiriro3** [comment]
I opened a bug on it -> - https://github.com/elastic/cloudbeat/issues/336
