### ISSUE TITLE
[BUG] Group by resources unable to show resources / findings 

### ISSUE THREAD

**Issue by tinnytintin10** [elastic/cloudbeat#160]
**Describe the bug**
When switching from the group by none view to the group by resource view, Kibana displays `There are no findings` 

**Preconditions**
I am running the main branch of Kibana locally with findings data coming from the cloud beat kind-mono cluster. 

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. View Findings grouped by none 
2. Group findings by resource 

**Expected behavior**

We should see a resource per row and their associated findings when you click on them. 

**Screenshots**

https://user-images.githubusercontent.com/53792284/169243173-a4d10c72-8315-4a53-90a1-e41085dd2b18.mov

**Additional context**

**Comment by tinnytintin10** [comment]
@tehilashn @kfirpeled I have added this to our last-mile epic with a priority 0

**Comment by ari-aviran** [comment]
This is happening due to the recent changes that were merged roughly at the same:
1. https://github.com/elastic/kibana/pull/130968
2. https://github.com/elastic/kibana/pull/131504

The queries for the findings-grouped-by-resource table rely on `resource.id.keyword` but in the mapping `resource.id` is only defined as text. The correct solution for this issue is to probably update the mapping of `resource.id` to include a `.keyword` field, both in the raw findings index mapping (comes from the integration) and in the latest findings index mapping (defined in Kibana code)

fyi @uri-weisman @eyalkraft

**Comment by kfirpeled** [comment]
Checkout https://github.com/elastic/security-team/issues/3737 for more information of planned work on the findings mapping

**Comment by kfirpeled** [comment]
fixed
- https://github.com/elastic/kibana/pull/132529

**Comment by tinnytintin10** [comment]
Since https://github.com/elastic/kibana/pull/132529#issuecomment-1133858488 is merged we can either close this issue out or keep it open till we add back `cluster id` to the table. I will leave that down to you - lmk if you want another issue to track adding back cluster-id to the table.

**Comment by kfirpeled** [comment]
@tinnytintin10 I've updated this [ticket](https://github.com/elastic/security-team/issues/3766) to address the cluster id
