### ISSUE TITLE
[CIS AWS] Operation error KMS: GetKeyRotationStatus, https response error StatusCode: 400

### ISSUE THREAD

**Issue by romulets** [elastic/cloudbeat#1749]
**Motivation**
[example](https://qa-cycle-812-oleg-cfi-8-12-0.kb.us-west2.gcp.elastic-cloud.com:9243/app/discover#/doc/logs-*/.ds-logs-elastic_agent.cloudbeat-default-2023.12.24-000001?id=RBjWoYwByeskzjUxpWvg) log line

For some reason [aws/acm AWS Managed Key](https://eu-west-1.console.aws.amazon.com/kms/home?region=eu-west-1#/kms/defaultKeys/e8d9a14d-b46e-4923-9315-a7ffc7b7ba90/keyPolicy) has no permission to visualize the Rotation Status.

The error:
```
operation error KMS: GetKeyRotationStatus, https response error StatusCode: 400, RequestID: d35391f4-77ba-45e3-a5e7-8ea67a01097d, api error AccessDeniedException: User: arn:aws:iam::704479110758:user/gh_ci_restricted is not authorized to perform: kms:GetKeyRotationStatus on resource: arn:aws:kms:eu-west-1:704479110758:key/e8d9a14d-b46e-4923-9315-a7ffc7b7ba90 because no resource-based policy allows the kms:GetKeyRotationStatus action
```

I validated that it's indeed the only problematic key with

```
aws kms list-keys --region eu-west-1 | jq '.Keys.[].KeyArn' | xargs -L1 aws kms get-key-rotation-status  --region eu-west-1 --output text --no-cli-pager --key-id
```

I spent some time trying to understand why this specific key has no access, but I could not find anything useful. All I know is that because it's a AWS Managed key we can't configure rotation ourselves.

I was thinking on alternatives on how to do this but I could not find a way to validate the key before performing the call.

The good side is that the error doesn't break the flow, [it's gracefully handled and the rest of operations are performed](https://github.com/elastic/cloudbeat/blob/main/resources/providers/awslib/kms/provider.go#L78).

**Definition of done**
- [ ] Understand why this KMS key return an error on get-key-rotation-status

**Related tasks/epics**
- Found on https://github.com/elastic/security-team/issues/8219#issuecomment-1870039617
- Investigated on https://github.com/elastic/security-team/issues/7932#issuecomment-1870398671

**Comment by orouz** [comment]
we're getting this error because this resource (`aws/acm`, a KMS AWS managed key) is lacking the `"kms:Get*"` action permission. for example, `aws/dynamodb`, also an AWS managed key, does have that action permission so we can call `get-rotation-status` on it. 

the resource policy is created by AWS and can't be changed. we could probably avoid this error by calling `GetKeyPolicy` to verify the next call to `GetKeyRotationStatus` will be successful, but that would mean many more requests just to avoid this error, which as mentioned, doesn't break anything. 

i think it's ok to close this issue and accept this error given we know why it happens. @oren-zohar ?

**Comment by orouz** [comment]
after discussing with @oren-zohar we came to realise that we don't need to evaluate KMS keys not managed by the user (as in - aws managed). will push a PR with a bug fix

**Comment by kfirpeled** [comment]
will be tested as part of long running tests

**Comment by Omolola-Akinleye** [comment]
Verified


![Image](https://github.com/elastic/cloudbeat/assets/17135495/9a23f10e-5c89-4f86-accb-25308623fa79)
