### ISSUE TITLE
Create serverless environment workflow fails

### ISSUE THREAD

**Issue by amirbenun** [elastic/cloudbeat#1913]
### Describe the bug
As part of the "Create Environment" workflow, when running with serverless checkbox selected, it installs agentless CSPM on the agentless agent.
Next if the "run tests" checkbox is selected, it verifies that the agentless agent run the CSPM component and creates findings.

The workflow fails to validate that the agent run a CSPM component.
> FAILED integration/tests/test_sanity_checks.py::test_cspm_aws_findings[identity-management] - AssertionError: Expected 2 agents running cloudbeat/cis_aws, but got 0

**Comment by gurevichdmitry** [comment]
The bug is no longer reproducible. It may be related to the fix implemented [here](https://github.com/elastic/cloudbeat/pull/2185). To ensure that nothing was missed, I ran the `Create Environment` workflow with both the latest [snapshot version](https://github.com/elastic/cloudbeat/actions/runs/9003205278/job/24733311675) and the current [8.14.0 BC version](https://github.com/elastic/cloudbeat/actions/runs/9014225808/job/24766491706), and both runs passed, including sanity checks. Additionally, I validated the fix by executing the `serverless weekly workflow` [here](https://github.com/elastic/cloudbeat/actions/runs/9001230631), which also passed successfully. Therefore, I'm closing this issue for now.
