### ISSUE TITLE
Supporting `conditions` configuration in CSPM/KSPM

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#2144]
**Motivation**
Following a fearture request from @BenB196 https://github.com/elastic/cloudbeat/issues/2128

**Definition of done**
- [ ] Add the `conditions` vars into the integration manifest, as seen [here](https://github.com/elastic/integrations/blob/9817e962729452e6ba164ebe1afd96e3740ddcc3/packages/kubernetes/manifest.yml#L40-L44), for all of our integrations.
- [ ] Add conditions configuration under advanced options into our integration deployment page

**Related tasks/epics**
- https://github.com/elastic/cloudbeat/issues/2128

**Comment by kubasobon** [comment]
@maxcold I have prepared a PR [adding `condition` variable](https://github.com/elastic/integrations/pull/10298) to our integration. However I'd like to understand how it's used and what remains to be done to fulfill the Definition of Done. Would you be so kind and find time to chat with me about it?

**Comment by maxcold** [comment]
From the cloudbeat side, will providing this variable work out of the box? 

From the UX side as we have our custom integration design, I guess we need to involve product and design to find the proper place for such settings. In the default "Add integration" design there is a specific section "Settings" where user can change the settings per input (defined as vars in the manifest). We have a custom design for each var, therefore we will need to design and implement the conditions consistently across the inputs we support

**Comment by kubasobon** [comment]
Yes, it works out of the box, since it's evaluated and handled entirely by Elastic Agent.

You are correct - UX side would require design to accommodate for setting the variable on each of the inputs. Maybe _Kubernetes_ integration can be of help here, as it already exposes `Condition` variable like this.

<img width="741" alt="Screenshot 2024-07-08 at 13 36 57" src="https://github.com/user-attachments/assets/89537cd0-d57d-46da-b483-b03944c0f32b">
