### ISSUE TITLE
[BUG] Large amount of findings for single rule

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#226]
**Describe the bug**
We've noticed with @ofiriro3 a large number of findings on our clusters.
I've filtered a certain cycle_id and a certain rule_id and saw 106 records.

**Preconditions**
Cloud environment with the local kind agent running the integration

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Create a cloud environment
2. Install the integration on a local kind cluster agent
3. Wait for the findings 

**Expected behavior**
We should be able to see a single finding for a certain rule in a cycle.

**Screenshots**
<img width="1728" alt="Screen Shot 2022-06-20 at 16 57 07" src="https://user-images.githubusercontent.com/12246907/174626752-96acd0fb-b1ec-4041-8899-b49ab6cc2720.png">

**Comment by oren-zohar** [comment]
this is by design, these rules audit Pods, and ServiceAccounts. The initial design was to audit a list of resources per rule, but then we changed it to audit per resource, i.e. each bad resource will generate its own finding. Also, we should take into account [this](https://github.com/elastic/cloudbeat/issues/219), so it's actually 53, findings, right? This was an old decision, so I hope I remember correctly, can't find the discussion, @kfirpeled?
