### ISSUE TITLE
[BUG] Cloudbeat logs are level error

### ISSUE THREAD

**Issue by eyalkraft** [elastic/cloudbeat#231]
**Describe the bug**

Info level logs are written to sterr

**Preconditions**

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Run elastic agent with cloudbeat

**Expected behavior**
 Info logs should be marked as info level

**Screenshots**
<img width="1177" alt="Screen Shot 2022-06-21 at 9 57 48" src="https://user-images.githubusercontent.com/63912106/174753950-ecbf2322-e107-465b-b477-4f79ebcb33f2.png">

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Kibana Version: 
 - Endpoint Version:
 - Other Version: 

**Additional context**

**Comment by oren-zohar** [comment]
We should also fix the OPA errors formatting issue while we are at it

**Comment by oren-zohar** [comment]
related: https://github.com/elastic/security-team/issues/4168

**Comment by uri-weisman** [comment]
It seems that cloudbeat logs are not filtered under the right dataset.
In addition, upon clicking on the integration logs I would expect it to be already filtered by the cloudbeat dataset.

**Screen record**


https://user-images.githubusercontent.com/68195305/174760516-0e5615e3-6a50-4aaa-abd1-3639fa895033.mov

**Comment by CohenIdo** [comment]
Verification passed using Kibana Commit sha: 58f7eaf0f8dc3c43cbfcd393e587f155e97b3d0d

**Comment by yashtewari** [comment]
There was some discussion of the Agent getting new capability that captures stderr. The screenshot in the video capture seem to be showing this new feature in action. It makes sense too @uri-weisman, the log is classified under Elastic Agent because the Agent is reporting (in its own logs) that it has captured something from cloudbeat stderr.

We need to figure out why some logs are being sent to `stderr`. I'm seeing two sources: one is the OPA decision logs, these have their own ticket:
- https://github.com/elastic/security-team/issues/4168

The other is a warnings from Kubernetes, possibly from `Watcher` [initialized here](https://github.com/elastic/cloudbeat/blob/10543e28d8d29ec01b5420e322e9f85acd7a5b35/resources/fetchers/kube_fetcher.go#L108) or any K8S clients that we have elsewhere in cloudbeat.

**Comment by CohenIdo** [comment]
Verified in 8.4 BC-1 version (https://github.com/elastic/kibana/commit/58f7eaf0f8dc3c43cbfcd393e587f155e97b3d0d) - fixed
