### ISSUE TITLE
[BUG] Leader election doesn't work correctly on a used environment

### ISSUE THREAD

**Issue by ofiriro3** [elastic/cloudbeat#336]
**Describe the bug**
When a Kubernetes cluster has an old Cloudbeat `lease`, the next cycle of any `Cloudbeat` instances will contain no K8s objects.

**Short background**
Every time interval(15s), each of the running Cloudbeat instances tries to acquire the `lease` object.
The Cloudbeat that acquired the `lease` will be the only Cloudbeat instance from this `daemonset` that will fetch the K8s object.
More can be found here - [leader election](https://github.com/elastic/security-team/issues/4125)

**In-depth**
When degrading cloudbeat instances, the old `lease` object is not deleted. 
Then when a new deployment is starting, no Cloudbeat instance will fetch K8s objects since the lease is still "attached" to the old Cloudbeat instance that was deleted in the last deployment.

When the new deployment is starting, at some point the `lease` will be acquired by one of the new Cloudbeat instances - but sometimes no Cloudbeat instance acquires the `lease` before the starting of the first cycle. 

**Preconditions**
- A running Kubernetes cluster

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Run the CSP integration on your Kubernetes cluster (Spawn a new agent with the CSP integration).
2. Delete the agent.
3. Run the agent again.
4. Go to the findings page, and you will see that no `K8s` objects were fetched in this cycle.

**Expected behavior**
One of the `daemonset` Cloudbeat instances should fetch the K8s objects.

**Desktop (please complete the following information):**
 - OS: Mac darwin
 - Browser: Chrome
 - Kibana Version: commit 0011c16d2b4b19b169bd801766cb4db8792a2adc

**Additional context**
I discuss this bug with @uri-weisman and he will investigate more.

**Comment by eyalkraft** [comment]
Thanks for opening @ofiriro3!

Some relevant questions:
1. Does this reproduce if you wait 15+ seconds between the termination of the agent to the deployment of the next one?
2. How Is the UX effected by this behavior? In this case the user already has k8s objects findings (and latest). 
3. Given there is an old but valid lease when cloudbeat starts, What are the suggested solutions? Deleting the lease on a shutting down cloudbeat is possible but will probably only result with another race (the lease of a new holder is deleted by an old terminating agent, etc…)

**Comment by ofiriro3** [comment]
Hi, @eyalkraft thanks for addressing this issue so fast.

1. Yes.
2. When deploying a new agent, the findings will be aggregated to the accumulative latest findings like the image below.
A single cycle should not consist so many findings, but since it comes from a different agents, it is aggrigated here. 
<img width="490" alt="image" src="https://user-images.githubusercontent.com/19221736/184537735-6edb9ef2-8daa-4911-838a-c90213b74014.png">

And obviously, when using specific dashboards that filter on a specific agent/cycle it will be clear that there are no K8s objects.

3. I didn't investigate the code enough to suggest a proper solution. I guess that we can always wait for 15 sec before starting the first cycle, but I didn't dedicate enough thought to all the implications of such a solution.

**Comment by uri-weisman** [comment]
Thanks @ofiriro3 and @eyalkraft.

**What we know:**
1. The lease is not released by the holder when the agents are degraded.
2. The issue does not reproduce when running a standalone Cloudbeat - the lease is released when the deployment is deleted.

The k8s leader election util exposes the [ReleaseOnCancel](https://github.com/kubernetes/client-go/blob/master/tools/leaderelection/leaderelection.go#L154) config which we use in our implementation.
By setting this config to `true` the leader should release the lease upon context cancellation, as described above it does not happen.
I assume that a `SIGTERM` is sent when we degrade the agents and for some reason, it's not propagated to cloudbeat to perform a graceful shutdown.

IMO, the leader election pkg has a bug as well, it should not call the `OnNewLeader` callback even if the lease exists because the acquire time isn't valid.

I suggest the following:
1. Commit the following [PR](https://github.com/elastic/cloudbeat/pull/338) as a workaround to 8.4.0.
In this fix, we stall the cycle until the non-leader candidates acquire leadership.
2. Open a task to complete this investigation and provide a proper solution for signal handling.

**Comment by eyalkraft** [comment]
Thanks @uri-weisman 
As agreed in the sync:
1. We will not release a fix for 8.4 due to the low probability of  a user experiencing this issue. Until the release happens, @uri-weisman is responsible for checking we have no related missing-k8s-resources problems showing up on our running 8.4 release candidate cloud environment.
2. Additionally, to test the fix, @uri-weisman will run a separate cloud environment with agent+cloudbeat including his PR.
3. We need to open an issue to research and fix the "Graceful cloudbeat shutdown upon agent termination" (@uri-weisman can you please open it with the relevant details you found?)
4. We need to come up with a long term solution fix, ideally one that:
   1. Doesn't require cloudbeat to wait before it starts.
   2. Is robust to non-graceful shutdown.
   
   Optional suggestion: Make cloudbeat check the validity of the leader election lease upon start up, and not just it's existence.
   This issue will be used to follow up on that.

@elastic/cloudbeat
