### ISSUE TITLE
CIS AWS - Running cloudbeat in hosted agent research/POC

### ISSUE THREAD

**Issue by ari-aviran** [elastic/cloudbeat#410]
As part of implementing data collection for CIS AWS benchmark, we'd like to provide a friction-less deployment story for the user. In the long term, we'd like to run the service that collects the data (today - `cloudbeat`) in Elastic's infrastructure, similar to the way synthetics works today. Today said infrastcuture does not yet exist - and our next best option is to run `cloudbeat` as part of the hosted agent that is deployed as part of the Elastic stack.

The goal of this task is to research and have a working POC of running `cloudbeat` as part of the hosted agent once a user installs our integration, and find out if there are any gaps we need to solve first.

**Out of scope**
- AWS data collection
- Building trust with AWS accounts (auth)

**Comment by eyalkraft** [comment]
Summarizing some ideas/leads that came up discussing with @joshdover:

## POC

- [ ] **Direction - Lift Kibana restrictions**

Kibana has the code that enforces the hosted agent to only run specific integrations (`is_managed`) on the hosted agent, and not allow others ([lead](https://github.com/elastic/kibana/blob/e0446dac822f55f75c1d97b6d9c3f4647c445973/x-pack/plugins/fleet/server/services/agents/hosted_agent.ts#L24)). For the POC we can:
1. Change Kibana to remove said restrictions
2. Deploy to the cloud using `ci:deploy-cloud` label
3. Manually add our integration to the deployed Kibana.

Possibly you'll have some problems cause by the [cloud infra](https://github.com/elastic/cloud-assets/blob/68310330d5c817075519eec7d23010246ae12960/stackpack/apm/config/capabilities.yml).

- [ ] **Direction - Change cloud infra**

[This](https://github.com/elastic/cloud-assets/blob/68310330d5c817075519eec7d23010246ae12960/stackpack/kibana/config/kibana.yml#L242) is where the default hosted agent integrations defined.
By changing it we can add our integration to the hosted agent's policy.
This direction requires additional research regarding how this can be tested. Maybe check out [#cloud-first-testing](https://elastic.slack.com/archives/C0198UAH3L4).

- [ ] **Direction - profiling team** 

Another direction to check out is to talk and team up with profiling team about how they will deploy their integration to hosted agent since they're also planning something similar in the near future (more details here https://github.com/elastic/cloud/issues/86611 )

## After POC

### Metrics and performance
One concern with running cloudbeat on the hosted agent is performance and resource consumption.

1. First step would be to test the metrics and behaviour of cloudbeat running inside the hosted agent of the tested cloud deployment (https://admin.found.no/ can be useful for that).
2. After concluding the first steps, possible cloudbeat optimizations (if needed) can include host-resources usage limiting, changing the fetching cycle to be sparse (not collecting all cloud resources at once but gradually), and more.

### Leader election
As the hosted agent can scale horizontally, there could be a situation where multiple hosted agents are running with the same agent policy. With K8s we've solved the duplicate-collection problem using a leader election mechanism.
Since the hosted agent doesn't run on K8s it requires a different (yet similar) solution.
Most of the infrastructure for that is already in the agent as [documented](https://docs.google.com/document/d/1aI-X4Lk6l-yHPNI5PuHi-tUS3clYOkyYlaSh8y4XPZQ/edit), but still some final implementation is missing.
This will be required if we move on with the hosted agent, and could be a good opportunity for cooperation with the ingest team. 

## Future

- [ ] Far future follow up - After https://github.com/elastic/ingest-dev/issues/1091 is completed, POC with the new k8s-based managed ingestion. We can already open another issue to follow that.

**Comment by eyalkraft** [comment]
**Update**:
After discussing again with @joshdover, given the current priorities and timeline for the platform team (great focus on native k8s agent, no resource allocation for hosted agent autoscaling and "beats watchdog" for the hosted agent),
Seems like the better future investment would be to wait for the new Managed Kubernetes Infrastructure (MKI) the team will be working on.

We agreed to stay updated regarding this matter, and make sure the CSP team will be an early cooperator and user of the MKI.

@amitkanfer
