### ISSUE TITLE
OPA decision logger attempting to send logs to bundle server

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#416]
**Describe the bug**
I've investigated the logs and saw that when we turn off the decision logger (this is how we run by default), OPA's behavior in that case is to attempt and send the decision logs to the bundle server that is configured by us.
This is the configuration that we have right now (%t by default is false):
```
var opaConfig = `{
	"bundles": {
		"CSP": {
			"resource": "file://%s"
		}
	},
	"decision_logs": {
		"console": %t
	}
}`
```
You can see this in the documentation of OPA (https://www.openpolicyagent.org/docs/v0.13.5/configuration/#decision-logs).
It states the following: **"Name of the service to use to contact remote server. If no plugin is specified, and console logging is disabled, this will default to the first service name defined in the Services configuration"**.

If you will run cloudbeat with OPA you will be able to see that it attempts to send the logs to an unresolvable endpoint and having problems with it:
```
{"log.level":"info","@timestamp":"2022-09-22T10:18:11.574Z","log.origin":{"file.name":"process/stdlogger.go","file.line":54},"message":"cloudbeat stdout: \"{\\\"@timestamp\\\":\\\"2022-09-22T10:18:11Z\\\",\\\"log.level\\\":\\\"error\\\",\\\"log.logger\\\":\\\"opa_logger\\\",\\\"message\\\":\\\"Log encoding failed: upload chunk size too small.\\\",\\\"plugin\\\":\\\"decision_logs\\\",\\\"service.name\\\":\\\"cloudbeat\\\"}\\n\"","agent.console.name":"cloudbeat","agent.console.type":"stdout","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-22T10:18:14.189Z","log.origin":{"file.name":"process/stdlogger.go","file.line":54},"message":"cloudbeat stdout: \"{\\\"@timestamp\\\":\\\"2022-09-22T10:18:14Z\\\",\\\"log.level\\\":\\\"error\\\",\\\"log.logger\\\":\\\"opa_logger\\\",\\\"message\\\":\\\"log upload failed, server replied with not found.\\\",\\\"plugin\\\":\\\"decision_logs\\\",\\\"service.name\\\":\\\"cloudbeat\\\"}\\n\"","agent.console.name":"cloudbeat","agent.console.type":"stdout","ecs.version":"1.6.0"}
```

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Just deploy cloudbeat and look at the logs.

**Expected behavior**
OPA should be able to handle logs without any errors, and shouldn't trigger log sending requests to a non-existing endpoint.

**Comment by amirbenun** [comment]
With https://github.com/elastic/cloudbeat/pull/423 merged, we show the decision logs on Fleet UI, but most of the fields are hidden since we didn't explicitly specify them on the integration. ([example](https://github.com/elastic/cloudbeat/issues/170)).
The next step is to add it to the integration and make sure it's well shown.

![image](https://user-images.githubusercontent.com/34831306/200825256-e82fede4-e528-4171-959a-d36318e8b05b.png)

**Comment by oren-zohar** [comment]
thanks @amirbenun, do we have a ticket for it?

**Comment by amirbenun** [comment]
We discussed it over the daily and a few options were suggested:
In order to enable decision logs we raised two options:
a. Add a checkbox on the integration to enable decision log
b. Enable decision logs by default on debug log level (remove the `decision_log` flag)

Once we have the decision logs enabled, in order to view them we have 3 options:
1. Edit the integration to show the new fields
2. Change the log message field to contain more information (input, output)
3. Leave it and view the log through the Discover window as it only regards developers

I think we should start by implementing option (b) ASAP.
Later on, we can complete the discussion regarding how to view the logs.
What do you think? @oren-zohar @eyalkraft

**Comment by eyalkraft** [comment]
Thanks @amirbenun 

> I think we should start by implementing option (b) ASAP.
Later on, we can complete the discussion regarding how to view the logs.

agreed.


> 1. Edit the integration to show the new fields
>2. Change the log message field to contain more information (input, output)
>3. Leave it and view the log through the Discover window as it only regards developers

Regarding viewing the logs I'd change the list a bit (also based on some suggestions during the daily):

1. Edit the integration to **map** the new fields _- this way they're not only viewable in Discover but also searchable._

This is also the option i'll go for. But not urgent at all.

**Comment by amirbenun** [comment]
Created a continuation task and closing this one
- https://github.com/elastic/cloudbeat/issues/533
