### ISSUE TITLE
Move all build functionality to mage

### ISSUE THREAD

**Issue by DaveSys911** [elastic/cloudbeat#466]
Description:

In an effort to centralize the project's build logic in one place, all build commands will be migrated to mage.

DoD:

- [ ] Remove makefile
- [ ] Ensure artifact is the same as before the change (same commit)
- [ ] Add comments to document mage targets

**Comment by eyalkraft** [comment]
While cloudbeat's build process should be centralized, I think it requires a bit of planning rather than

> all build commands will be migrated to mage.

Mage is written in Golang, while some parts of our build are dependent on running other binaries (building the bundle with OPA for example).
While mage does provide [helpers](https://magefile.org/libraries/) including a [shell helper](https://carolynvanslyck.com/blog/2021/01/mage-is-my-favorite-make/#shell-helpers), Running shell from within the magefile ([cloudbeat example](https://github.com/elastic/cloudbeat/blob/main/magefile.go#L342-L350)) doesn't seem so clean and simple at a first glance.

I recommend the implementer to check out this [blog](https://universalglue.dev/posts/magefile/) when implementing.

I suggest adding a first step to the DOD

- [ ] Come up with a suggestion for a cleaner, simpler and centralized build process for cloudbeat. Discuss it on this Issue and come to conclusions.

**Comment by DaveSys911** [comment]
@eyalkraft
Good point,  I think we should avoid using the helpers when possible and use go includes instead. For example we can try to include the opa go package in our magefile and do the bundle build all in go.
