### ISSUE TITLE
Broken cloudbeat beat status test inside agent integration suite

### ISSUE THREAD

**Issue by DaveSys911** [elastic/cloudbeat#506]
Description:

Cloudbeat status check test fail so it's set to skip. Needs to be investigated & re-implemented. The kube exec command returns unexpected output.

https://github.com/elastic/cloudbeat/blob/main/tests/integration/tests/test_standalone_agent_integration.py?plain=1#L83

![Image](https://user-images.githubusercontent.com/16253938/200837367-1bd968fa-493f-489a-abc5-05f25f11afdb.png)

**Comment by gurevichdmitry** [comment]
Task progress:
1. Cloudbeat CI does **not** check standalone agent since the tests are executed on incorrect environment. It happens due to the following:

- strategy.matrix.include flow contains variable **values_files** that not used in test job - typo issue, since job uses **values_file** variable
- Thus test framework executes cloudbeat instead of stand alone agent because justfile recept **deploy-tests-helm** contains default helm values yaml file.
- Since cloudbeat-pod does not contain elastic-agent tool, when trying exec to pod exception occurred and the test fails and is marked as broken.
- After fixing typo error, job still continuing to execute tests on cloudbeat instead of standalone. This happens due to passing empty value for range, and command **deploy-tests-helm** receives 2 args instead of 3 and again default value is used.
- In order to execute correctly **deploy-tests-helm** need to change order of range and values_file params and also to provide them in strategy.matrix.include (default values are not usable)

2. After fixing CI issues stand-alone job tests are executed on correct environment but still failing.

- Passing tests: pods exist and running
- Failed tests:
    - Cloudbeat status - After investigation it was found that status format and fields were changed - will be fixed by updating test infrastructure
    - Finding are not retrieved - It seems like cloudbeat does not send findings. According to the logs cloudbeat sends notification only about lease acquisition. No fetcher logs appear.

**Comment by gurevichdmitry** [comment]
Working stand-alone agent CI on my [fork](https://github.com/gurevichdmitry/cloudbeat/actions/runs/3524942362/jobs/5911086863)
