### ISSUE TITLE
CloudFormation for CIS AWS

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#596]
**Motivation**
Having CloudFormation script will ease our integration onboarding. Similar to vulnerability 

**Defeintion of Done** 
- [x] Create cloudformation script
- [x] Update to S3 from the CI
- [ ] Update CSPM integration with new variable with the link "quick-creation"
- [x] Add new deployment method to Kibana - Open task for Kibana team

**Related:** 
- https://github.com/elastic/security-team/issues/5659
- https://github.com/elastic/sre/issues/1480
- https://github.com/elastic/security-team/issues/5637

**Comment by amirbenun** [comment]
With [CloudFormation mapping](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html) we can have a single template that suits for many use cases based on parameters.
I would consider it as an option instead of maintaining multiple elastic-agent templates that are 90% similar. 
In this specific case, CSPM and CNVM templates should be identical except of the elastic-agent role.
I would try to have a map that contain the two roles and we dynamically create the relevant role based on the installed integration.

**Comment by tehilashn** [comment]
@orestisfl - why is this task blocked?

**Comment by tehilashn** [comment]
Thanks Orestis. 
So if I understand correctly, Cloudbeat's part is done and we're now waiting for Kibana. 
In that case, I would close this task (and remove " Update CSPM integration with new variable with the link "quick-creation" from the DoD), since we have a task to represent this on Kibana's side.

**Comment by orouz** [comment]
- [ ] Create cloudformation script
 `https://github.com/elastic/cloudbeat/tree/main/deploy/cloudformation`

- [ ]  Update to S3 from the CI
 `https://github.com/elastic/cloudbeat/blob/main/.github/workflows/publish-cloudformation.yml`
 
- [ ]  Update CSPM integration with new variable with the link "quick-creation"
https://github.com/elastic/integrations/commit/e938366b876917271194c039d1b2f95b5338433c

- [ ]  Add new deployment method to Kibana 
   - verified in https://github.com/elastic/kibana/issues/157761
