### ISSUE TITLE
[Discuss] Sharing finding index for vulnerabilities

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#610]
**Summary**

Is sharing finding index for vulnerabilities making sense? what should we consider? what are the benefits, and what are the cons?

**Comment by eyalkraft** [comment]
I recommend we use the index `logs-cloud_security_posture.vulnerabilities-default` for our vulnerabilities findings.

1. Currently there are no designs that require querying for and displaying both vulnerabilities and misconfigurations in the same table. Since this is the case, I don't think it's wise to introduce a change to the findings index in a way that will require our Kibana team to make adjustments to the Kibana code so our current offering wouldn't break (aka vulnerabilities will accidentally show in the misconfigurations tab because they're in the same index).
2. In case there will be such product requirement in the future, we'll be able to create such index template that would allow us to query both vulnerabilities and misconfigurations `logs-cloud_security_posture.*-*` and display them in a single table using a single query to ES.

Let me know what you think @oren-zohar @kfirpeled @CohenIdo @tehilashn 

---

As part of this work I also came across a detail in our Figma designs on which I [commented](https://www.figma.com/file/t6serT7B5lkbK8qvqFuvxR?node-id=1057:275405#346189666).

The main question that arises is - Will we go on a _transform + latest index_ approach with vulnerabilities, just like KSPM/CSPM works, or will we query for the relevant vulnerabilities as suggested here:
- https://github.com/elastic/security-team/issues/5496

I think that if we successfully complete the POC soon enough and deduct that the query approach is valid, we should start with the query approach for vulnerability management even before migrating KSPM/CSPM to it.

**Comment by tehilashn** [comment]
> I think that if we successfully complete the POC soon enough and deduct that the query approach is valid, we should start with the query approach for vulnerability management even before migrating KSPM/CSPM to it.

+1 on that

**Comment by oren-zohar** [comment]
@eyalkraft what about the `cloud_security_posture` prefix, do we want to change it to the new team desc? do we even need it?
Regarding the second point, if we change it to `cloud_security` we could still use `logs-cloud_security*.*-*`, right?

@CohenIdo @kfirpeled does the new query approach prioritized for 8.8?

**Comment by CohenIdo** [comment]
Hey @oren-zohar, I just [summarized](https://github.com/elastic/security-team/issues/5496#issuecomment-1412262114) my POC regarding the query approach, TL:DR, it seems that for now we will remain with the Transform and still having the latest findings index, for more details pls read the "Conclusion and Recommendations" part. 

@eyalkraft It means that we will need to add one more Transform for the vulnerability management.

**Comment by eyalkraft** [comment]
@oren-zohar 

> Regarding the second point, if we change it to cloud_security we could still use `logs-cloud_security*.*-*`, right?

Sound's possible but we'll need to validate.

I think the prefix should be the integration name (regardless of our team's name)

**Comment by eyalkraft** [comment]
Going forward with the index `logs-cloud_security_posture.vulnerabilities-default` for our vulnerabilities findings.
