### ISSUE TITLE
[Discuss] Vulnerabilities DB update interval

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#624]
Define and implement/configure DB update flow
- Should it only happen on deployment?
- Should it happen once per cycle? (24h)
- Should it be packed with cloudbeat? to support on-prem?
- Can we just re-start cloudbeat? easiest approach

**Comment by amirbenun** [comment]
Here is a list of the most straightforward flows for downloading the vulnerabilities database Trivy uses in order to scan VMs.

## Bundled with Cloudbeat
Cloudbeat CI pipeline will download the database and pack it into cloudbeat.tar.gz (same as the rego bundle we are it uses)
**Pros:**
- Align vulnerability management flow with posture benchmarks flow (in a way).
- Fast initialization of Cloudbeat.

**Cons:**
- New vulnerabilities will only be detected by Cloudbeat after an upgrade of elastic-agent.
- Coupling Cloudbeat version to a database version.

## Before the first run
Cloudbeat downloads the database once in a lifetime and can’t update it
**Pros:**
- The user can restart the agent to trigger the download, and it pretty much lets the user control it.
- If you envision a button on the fleet UI to trigger the database download, all it has to do is restart Cloudbeat.

**Cons:**
- New vulnerabilities will only be detected by Cloudbeat after an elastic-agent restart.
- The feature won’t be supported for on-prem users.

## Before every cycle
Cloudbeat downloads the database before every vulnerability cycle starts. Trivy also supports [cache](https://aquasecurity.github.io/trivy/v0.35/docs/vulnerability/examples/cache/) in order to avoid high network bandwidth.
**Pros:**
- It keeps the database as updated as possible and new vulnerabilities will be detected on the next cycle (day).

**Cons:**
- An EC2 instance that downloads ~40Mb (worst case) a day will cost more to the user.
- The feature won’t be supported for on-premises users.

I think downloading the vulnerabilities database before every cycle is an optimal solution for us as it reduces the false negatives and makes our product more reliable.
Would love to hear more thoughts @eyalkoren @oren-zohar @jeniawhite.

**Comment by eyalkoren** [comment]
I believe you meant @eyalkraft 🙂

**Comment by olegsu** [comment]
I would suggest having a bit from every point.
Bundle it to make sure that even in a close network we have something to work it.
Next, download it on the first run.
Finally, updating it every N hours based on the environment variable (with 24H as default). Using env var will give the option to opt out of the everyday download to someone who doesn't want the cost increase or has an unstable network.

Another two thoughts that I have
* Do we know how often the DB is updated? 
* Does it have metadata? 
  * With version (semver or something else?) so we don't download versions with breaking change 
  * With other information to be added to the event

**Comment by tehilashn** [comment]
Thank you for the summary @amirbenun . 

I'd like to emphasize that imo the vulnerability mgmt. solution (in contrast to CIS benchmarks), can not update the vulnerabilities database only once, and cannot rely on an agent update/restart. 

We need to choose a solution (pull before every run, once every x hours) that is not dependent on an external operation to Cloudbeat. Of course, this does not necessarily needs to be supported for our first beta release, but is important for the GA solution. cc @nick-alayil 

 And +1 to @olegsu 's suggestion to bundle it either way, so we'll have a backup DB within Cloudbeat.

**Comment by nick-alayil** [comment]
My opinion is the same as @tehilashn's stated above, we should have the auto vuln db sync before every scan cycle since it directly impacts the value of the product. I assume there will be multiple Db syncs for trivy since there are multiple data sources. Certainly, this is not a must-have feature for the beta release.

**Comment by amirbenun** [comment]
Thank you all for the responses, I will try to sum up a conclusion of all you wrote here and see how it fits our next releases.
For the beta release, in version 8.8, we should start with a download before every cycle, keeping in mind that Trivy has a built-in cache layer for the DB.
In the next versions, taking the vulnerability management to GA (8.9?), we can also add a bundled database file to be available for offline environments.
In further releases, we can also let the user configure if he wants to update the database and how often.

That way we break down the feature in order to have progress over perfection, but bring high value and a reliable product to our customers even on the beta release.

**Comment by amirbenun** [comment]
I opened the relevant tasks derived from that discussion.
- https://github.com/elastic/cloudbeat/issues/696
- https://github.com/elastic/cloudbeat/issues/697
