### ISSUE TITLE
[Discuss] New integration package vs policy template

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#625]
**Motivation**

As we start implementing our new [Vulnerability Management](https://github.com/elastic/security-team/issues/5658) solution, we need to decide whether it will be part of a new integration package, or should it be part of the cloud posture integration.

This decision should take into account the common logic both solutions will share, such as the output index, mapping, used beat, and deployment options

**Related issues**
- https://github.com/elastic/cloudbeat/issues/610

**Comment by oren-zohar** [comment]
A thing to also consider, separating the packages will allow the user to deploy both CSPM and VM on the same policy, which can be problematic from deployment flow stand point

**Comment by eyalkraft** [comment]
Also consider the ongoing change in packages categories [PR](https://github.com/elastic/integrations/pull/5123/files#diff-72fc27a4cf2fb28244c8fa9ed27c00e43935777a4875c5d61d91372f0d483425)

**Comment by kfirpeled** [comment]
Please feel free to contact me regarding kibana's perspective on this issue

**Comment by kfirpeled** [comment]
Amir and I had a conversation offline.
**tl;dr**
We don't find any clear advantage for each option from UX perspective, each solution has its own pros and cons and there isn't a solution that fits all our needs. In most cases, you'll find that the difference is only semantic. Therefore, **I recommend sticking with our current solution (SP)** instead of having two different approaches to maintain and learn which will slow our development process. 

**SP (same package new policy_template)**
How I picture SP would look like
1. index name would look similar to: `logs-cloud_security_posture.vulnerabilities-default`. 
This creates a uniform naming in the code base across the multiple repos: `kibana` (our plugin name is also named `cloud_security_posutre),` `integrations` (the package name is the same: `cloud_security_posture`) and `cloudbeat`
   1. This will also allow us having a common prefix like `logs-cloud-security-posture*` for index templates and other usages
2. The infrastructure is already laid down for working with SP (deployment instructions, custom UI for the integration, different hooks we have, auto upgrade the package, and setting up dependencies) 
3. Installing one package installs all of our assets (like: csp-rule-template, task scheduler, transforms)

** Assuming we are using datastreams, their naming is set in the following format: `logs-<package name>.<datastream name>-<namespace>`
** tbh, if it wasn't such a headache to change it, I would say we should refactor everything to cloud_security instead of cloud_security_posture

**NP (new package)**
Assuming the name of the integration would be: `vulnerability_management`
1. index name would look similar to: `logs-vulnerability_management.vulnerabilities-default`. This might imply we are the single place for managing vulnerabilities, which is not quite correct. We manage vulnerabilities on cloud as part of cloud security.
2. Having a new package brings new challenges to support in fleet (unlike SP, we already did that as part of 8.7 release), like: 
    1. blocking the user from installing both `vulnerability_management` and `cloud_security_posture` on the same agent policy.
    2. laying down some infra we already did in several key points in kibana: deployment instructions, custom UI for the integration, different hooks we have, auto upgrade the package, and setting up dependencies
3. Sharing assets between integrations (aka packages) doesn't come OOTB
5. I find it less intuitive to have kibana plugin named `cloud_security_posture` handling the package named `vulnerability_management`

**Summary**
As you can see, most of my points are regarding naming conventions and semantics. Supporting both SP and NP doesn't bring any true value for us, just more work and edge cases to support. So for the sake of a faster development process, I recommend sticking with what we have until it no longer can serve our needs.

**Comment by eyalkraft** [comment]
Synced with @amirbenun, we're going forward with @kfirpeled's suggestion: SP (same package new policy_template)
