### ISSUE TITLE
GCP Planning

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#708]
Things to review:
- [x] GCP account
- [x] Rules - prioritize the different sections with product
- [ ] SDK / Existing Tool integration
- [x] Testing requirements
- [x] Deployment methods
- [x] Authentication

Related Epic:

- https://github.com/elastic/security-team/issues/5493

Refs:

- [Cloudquery-with-elasticsearch](https://www.cloudquery.io/blog/search-through-cloud-infrastructure-with-elasticsearch)
- [cloudsploit by Aqua](https://github.com/aquasecurity/cloudsploit)
- [CIS AWS research](https://github.com/elastic/cloudbeat/issues/409#issuecomment-1302230728)
- [monitoring-gcp-asset-changes](https://cloud.google.com/asset-inventory/docs/monitoring-asset-changes)
- [GSCC](https://cloud.google.com/security-command-center/docs/concepts-security-command-center-overview#standard-tier)

**Comment by uri-weisman** [comment]
### WIP ###

- GCP account - opened a [ticket](https://elasticco.atlassian.net/browse/PSEC-42) to the security platform team.

**Comment by uri-weisman** [comment]
@tinnytintin10, @oren-zohar, @tehilashn 

Is there any additional data you think we should get regarding the third-party vendors besides pricing model and benchmark coverage?

Vendor | Pricing | Benchmark version | Coverage %
-- | -- | -- | --
GSCC | [gscc pricing model](https://cloud.google.com/security-command-center/pricing)| v1.3 | Standard - 25% , Premium - 100%
CloudQuery | Free | v1.2 | Almost full coverage
CloudSploit | UnknownProvides an SDK (JS, Python, Ruby) for paid customers. | v1.3? | Not completely sure,repo is not well maintained

Ref:
[gscc pricing model](https://cloud.google.com/security-command-center/pricing)
[gcss tiers](https://cloud.google.com/security-command-center/docs/concepts-security-command-center-overview#standard-tier)
[cloudQuery cis gcp policies](https://github.com/cloudquery/cloudquery/tree/main/plugins/source/gcp/policies)

**Comment by eyalkraft** [comment]
@uri-weisman what about 
open source license type? (aka make sure can we use Cloudquery/Cloudspolit in our product)

**Comment by eyalkraft** [comment]
Another request from the product team @tinnytintin10 @snehsach19 is to try and list/articulate the compromises we do when using these tools to faster implement GCP CIS Benchmark. for example, some things from the top on my mind: Less control over which rules exist, Less control over benchmark version, For some use cases (Cloudquery IMO because it requires an SQL server alongside) only "cloud-native" installation (like cloudformation)...

**Comment by uri-weisman** [comment]
> @uri-weisman what about open source license type? (aka make sure can we use Cloudquery/Cloudspolit in our product)

@eyalkraft updated

**Comment by uri-weisman** [comment]
@tinnytintin10 @snehsach19 

When we don't have control over the "engine", we will inevitably encounter certain compromises. 
Here are a few examples of potential compromises:

**Control over benchmark version:**

When we rely on a third-party vendor for evaluation, we have limited control over the specific version they support and the rules they choose to exempt. However, if we decide to implement our own solution using their SDK, we gain full control over these aspects.

**Cloud-native installation:**

To fully utilize Cloudquery (resource collection + evaluation), we need to deploy a PostgreSQL server to store the assets and execute policies. This deployment process should be automated, along with the installation of the elastic agent,
It means that the integration could not be installed manually but using the GCP deployment manager.
Cloudsploit is running on NodeJS so it might be relevant in the future when serverless becomes available and cloudbeat could be run as a standalone.

**Events structure:**

When relying on third-party vendors for evaluation, customizing the event according to our own requirements becomes more challenging.
In case we'll use a tool solely for asset collection, we may gather more resources than needed, including vendor-specific custom fields, which will result in sending irrelevant data to ES.

**Resource consumption**

As we move towards a Serverless architecture where we manage resources such as memory and CPU, it becomes crucial to optimize consumption. by not owning the "engine", we will have limited control over that.

**Logs**

The logs from CloudSploit and CloudQuery will be obtained from a file, limiting our control over those logs. This can result in decreased visibility for our users and make product debugging more challenging.
Google's security center findings can be consumed using their API, which means that we can have more flexibility and control over processing the information and errors of those requests.

**Comment by eyalkraft** [comment]
Thanks @uri-weisman !

Could you try and estimate how faster/easier it would be to use an external tool that already implements the benchmark, comparing to implementing on our own?

Also regarding **Events structure** I do think this part would require our complete control (that's basically all that theres left - mutating the tool output to our required schema). I don't see a reason we'll have to send irrelevant or unformatted data to ES like you said.

Same goes for the **Logs** - we can have full visibility. But I do agree it might be harder to report a specific error to the user like we could when implementing ourselves.

Regarding **Cloud-native installation** I don't see a reason we couldn't use Cloudsploit even though it's running on NodeJS. This is the whole point with limiting the installation to this method - we could run whatever we want in whatever way we want. This isn't blocked by serverless IMO.

**Comment by uri-weisman** [comment]
Thanks @eyalkraft 
> Could you try and estimate how faster/easier it would be to use an external tool that already implements the benchmark, comparing to implementing on our own?

Without conducting a POC, it's challenging for me to provide an exact estimate. 
However, I would estimate that utilizing GSCC instead of developing our own solution would potentially result in approximately twice the speed. Furthermore, it would also save us time on maintenance since we wouldn't be responsible for updating the benchmark. 
As for other tools (cloudquery & cloudsploit), we will need to experiment with them to determine the required effort, but once we start using them, we can incorporate multiple benchmarks and cloud providers.

> Regarding **Cloud-native installation** I don't see a reason we couldn't use Cloudsploit even though it's running on NodeJS. This is the whole point with limiting the installation to this method - we could run whatever we want in whatever way we want. This isn't blocked by serverless IMO.

Agreed, but then we'll have to run it outside the agent, isn't it?

**Comment by eyalkraft** [comment]
> Agreed, but then we'll have to run it outside the agent, isn't it?

Correct

**Comment by tinnytintin10** [comment]
@uri-weisman thanks for the great context/overview. To clarify, by "twice the speed" you mean two times faster than it would take us to build this from the ground up, right?

**Comment by uri-weisman** [comment]
> @uri-weisman thanks for the great context/overview. To clarify, by "twice the speed" you mean two times faster than it would take us to build this from the ground up, right?

Indeed @tinnytintin10.

**Comment by tinnytintin10** [comment]
As clearly laid out in [last week's security email](https://groups.google.com/a/elastic.co/g/dev/c/cisgf2tsvic/m/aPNtQ6pzBgAJ), we face two questions concerning the integration of the CIS Benchmarking for GCP into our CSPM product:

1. Should we incorporate posture data from external solutions such as GSCC?
2. Is it a product requirement to implement a “stand-alone” solution to produce posture data independently?

Examining the first question, it becomes evident that incorporating posture data from an external service/product like GSCC into our CSPM product is not in our best interest. Relying on an external service creates a dependency, exposing us to the uncertainty of their decision-making and licensing policies. Furthermore, it could result in an additional financial burden for the users, who would have to pay for both the external service and Elastic. Given these factors, the answer to the first question is a resounding no; we must steer clear of external dependencies for posture data within our CSPM offering. However, it is worth mentioning that Jamie’s team is developing a GSCC integration that users can leverage to bring in GSCC findings. Down the line, we will prioritize incorporating data from such standalone third-party integrations into views and workflows. However, this is a separate matter and not within the purview of the current discussion. 

Pivoting to the second question, since we have established that relying on an external service/product is not preferable, it is apparent that a “stand-alone” solution is indeed a product necessity. That being said, it’s crucial to prioritize the speed/swift development of this capability. If employing third-party tools like CloudQuery or CloudSploit speeds up the process despite possible limitations (e.g., outdated benchmark versions), this approach should merit careful consideration by engineering. From a product perspective, the fact that these third-party open-source tools have not been frequently updated to the latest benchmark version could indicate that users are not overly concerned about employing the most current versions. Even for the benchmarks we currently support, we have received 0 user requests and or feedback to update the benchmark versions we support, even for CIS K8S 1.23 (the most outdated benchmark we support). This again could indicate that users are not overall concerned with using the latest benchmark available. However, this is one hypothesis among others. Moving forward, if user feedback highlights the need for updating a certain benchmark, we can prioritize this effort.  

In summary, product's advice is that the engineering decision here should primarily be anchored in selecting an approach that ensures the quickest possible implementation/delivery of CIS Benchmarking for GCP. IMO employing third-party tools is an acceptable initial strategy if it hastens the delivery of this capability (but then again, long-term maintenance might be an issue). 

And as always, whatever route we go down, we can evolve based on user feedback and emerging product requirements. 

@tehilashn @oren-zohar @uri-weisman @eyalkraft I hope this clarifies the product team's stance. Lmk where you might still have open questions. 

cc @snehsach19

**Comment by uri-weisman** [comment]
@eyalkraft @oren-zohar @tehilashn 
The following criteria can be a good starting point for evaluating third-party tools:

1. **CLI/SDK Capabilities**: Determine if the tool can be used as a CLI or if it provides an SDK. Using an SDK offers advantages such as simplified integration, type checking, and better error handling compared to a CLI.
2. **Future Roadmap**: Assess the vendor's commitment to supporting new benchmarks and upgrading existing ones.
3. **Multi-Projects/Organization Support**: Verify if the tool can fetch data from multiple projects or at the organization level.
4. **Concurrency**: Consider whether the tool supports concurrent fetching, especially if we decided that we want the ability to fetch assets from the entire organization simultaneously. 
5. **Logs**: Evaluate how the tool integrates with our existing logger. Determine if it provides effortless integration or if additional configurations or modifications are required to incorporate its logs into our log management solution.
6. **Data Modifications**: Determine if any modifications are necessary to align the tool's fetched data with the expected template. I guess that we want the CIS GCP findings to follow CIS AWS (@tinnytintin10).

Feel free to add some of your own if you think something is missing 🙏

**Comment by uri-weisman** [comment]
@tehilashn @oren-zohar @eyalkraft @tinnytintin10 

After reviewing potential external tools, like our recent examination of Cloudquery’s [POC](https://github.com/elastic/security-team/issues/6881), I’ve concluded that they may not offer the fast market entry we initially anticipated.

The challenges we face include data enrichment - a takeaway from Cloudquery’s POC. 
We found out that the findings are missing information about the GCP regions. This makes us wonder if we need to fetch that data or if we should contribute our code to Cloudquery to fix issues of this kind.

Furthermore, the deployment of these external tools requires packaging both the tool’s binary and the PostgreSQL server for seamless operation. This is true regardless of whether we opt for a cloud-native deployment or bundle it with the agent.

It’s important to note that our existing infrastructure already covers the implementation of the CIS AWS benchmark. This infra not only equips us with valuable experience in executing a CSPM benchmark but also reduces the time and effort required to roll out new benchmarks. Had we not previously implemented any benchmarks, the integration of a single tool offering multiple benchmarks could have been more appealing. But considering the significant investment we’ve made in our current infrastructure, I find the task of implementing benchmarks to be easier and more straightforward.

It’s also noticeable that the CIS benchmarks are not being updated occasionally in 3rd party tools, so once we implement the newest benchmark it won’t require us to update it frequently.
I also explored Cloudsploit, but experienced [difficulties](https://github.com/aquasecurity/cloudsploit/issues/1578) gathering GCP assets. My initial impression suggests that further exploration in this direction might not be time-efficient.

In conclusion, I recommend we lean into the initial idea of implementing the benchmark using the GCP SDK. It’s more in sync with our infrastructure, offers an easier path, and mitigates the issues we’ve encountered with external tools.

**Comment by kfirpeled** [comment]
@uri-weisman, @eyalkraft do you expect any performance/throughput issues with the tools?
Anyway, it is worth mentioning your assessment regarding performance. I assume scaling out can be a challenge to explore in-case we will encounter throughput issues.
