### ISSUE TITLE
GCP Authentication util

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#765]
**Motivation**
To ensure consistency across all GCP providers, a shared utility will be developed that utilizes the GCP SDK to authenticate the client using the [specified authentication methods](https://github.com/elastic/security-team/issues/6093). This utility will provide a standardized and efficient way for all providers to obtain the necessary credentials and access GCP resources to retrieve relevant findings.

**Definition of done**
What needs to be completed at the end of this task
- [ ] Restructure cloudbeat config struct to support the agent's updated config.
- [ ] Common utility that supports the relevant GCP auth methods.

**Related tasks/epics**
- [filebeat implementation](https://github.com/elastic/beats/blob/5dd5e889c039f40a75b62374b529bf1c65b6a2f1/x-pack/filebeat/input/httpjson/config_auth.go)

**Comment by orouz** [comment]
seems like we need to wrap the GCP SDK in order to authenticate because our integration sends credentials values as optional (this is how it's done in AWS) so we need to figure out which one to use. 

an alternative approach would be the prevent the user from installing the integration if credentials are required but weren't provided. we already prevent the installation on a different [case](https://github.com/elastic/kibana/blob/0152724d47c9dde677e73b25b579c42f01097d55/x-pack/plugins/cloud_security_posture/server/plugin.ts#L118-L120), so we could do the same here. if we do, cloudbeat could pass the credentials values directly to the GCP SDK with very little need for wrapping. 

when a user will try to install an integration without providing credentials (when they are required), they will get an error notification when trying to install the integration. (like the one they get for "package policy already exists by that name")

@tinnytintin10 thoughts on this?
