### ISSUE TITLE
Cloudbeat does not stop when sending SIGINT

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#783]
**Describe the bug**
Cloudbeat does not stop when we send a SIGINT signal (CTRL + C).

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Run cloudbeat as a binary `./cloudbeat -c "deploy/aws/cloudbeat-aws.yml"`.
2. Try and stop the program using CTRL + C.

**Expected behavior**
The program should shutdown gracefully when a SIGINT signal is sent.
When hitting CTRL+C second time we should exit

**Additional context**
 - OS: darwin

**Comment by ari-aviran** [comment]
@uri-weisman there is a grace period of 30 seconds while it waits for fetchers to finish - is this not working? Do you expect some different behavior?

**Comment by orouz** [comment]
> The program should shutdown gracefully when a SIGINT signal is sent.

couldn't reproduce a case where cloudbeat doesn't shutdown eventually. it also seems cloudbeat exists after 30 seconds, which is the current grace period. when changed to 10 seconds, it also works:
```
{"@timestamp":"2023-04-27T12:35:35.603+0300","log.logger":"service","log.origin":{"file.name":"service/service.go","file.line":52},"message":"Received signal \"interrupt\", stopping","service.name":"cloudbeat"}
...
...
...
{"@timestamp":"2023-04-27T12:35:45.611+0300","log.origin":{"file.name":"runtime/panic.go","file.line":890},"message":"cloudbeat stopped.","service.name":"cloudbeat"}
```
it does show some odd logs where cloudbeat stopped due to panic. opened https://github.com/elastic/cloudbeat/issues/905

> When hitting CTRL+C second time we should exit

currently we're being notified by [libbeat](https://github.com/elastic/elastic-agent-libs/blob/main/service/service.go#L46-L55) who catches the signal and calls our stop function which starts the graceful shutdown process. AFAIK - after this point, we won't be notified again if more signals were sent. 

seems like we could be if we changed [this](https://github.com/elastic/elastic-agent-libs/blob/ee5dad913b28384320be73519fb255457046b8b3/service/service.go#L50) to use `for range sigc` instead. 

although generally bad maybe it'd be sufficient just resorting to `pkill -9 cloudbeat` whenever we **need** to kill the process.

**Comment by olegsu** [comment]
Verified by:
1. Running elastic-agent on local kind cluster
2. Sending sigint directly to the process
3. The process exit
4. New process has been started
