### ISSUE TITLE
[Cloud Security][Findings] Findings are missing id

### ISSUE THREAD

**Issue by opauloh** [elastic/cloudbeat#791]
**Kibana version:**
8.7

**Elasticsearch version:**
8.7

**Describe the bug:**

This error happens on Findings page when grouped by resource

TBD

**Steps to reproduce:**
1. TBD

**Expected behavior:**

**Screenshots (if relevant):**

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/19270322/222654080-c9d453b5-99fd-4723-866e-1bac1621ec6a.png">

**Errors in browser console (if relevant):**

<img width="1486" alt="image" src="https://user-images.githubusercontent.com/19270322/222654471-9425c063-a566-4e95-a8e5-575a7e09c3a5.png">

**Provide logs and/or server output (if relevant):**
TBD 

**Any additional context:**

When not grouping by resources, I can see some empty results for resource.id and resource.name (not sure if relevant)

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/19270322/222655051-763381b1-370b-4426-94b5-ae56ca87d7e3.png">

**Comment by uri-weisman** [comment]
@ari-aviran @tehilashn 
It's a Cloudbeat issue, happening due to the following piece of [code](https://github.com/elastic/cloudbeat/blob/783120117f20b47308c698df5bcd05bf994eaae0/resources/fetchers/monitoring_fetcher.go#L91-L96).
In case there are no Cloudtrails resources in the account we're sending an empty id & name - IMO this code should be removed.

**Comment by ari-aviran** [comment]
Verify that we don't have any other types of resources without IDs
