### ISSUE TITLE
Document deployment instructions

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#833]
**Summary**
We need to update our [dev docs](https://github.com/elastic/cloudbeat/tree/main/dev-docs) to include the full deployment instructions 

**Definition of done**
- [ ] Step-by-step instructions for deploying our VM integration with CloudFormation, to the point of having vulnerabilities sent to ES
- [ ] Step-by-step instructions for deploying for developing purposes, on a local machine
- [ ] Make sure to remind the users to delete the created snapshots using this:

```bash
for K in $(aws ec2 describe-snapshots --filters Name="description",Values="*Cloudbeat Vulnerability Snapshot.*" --query 'Snapshots[*].SnapshotId' --output text); do
aws ec2 --region eu-west-1 delete-snapshot --snapshot-id $K
done
```

> **_Note_** Please take into account that Kibana developers be the main users of this document

**Comment by amirbenun** [comment]
This document explains how to deploy elastic-agent that runs vulnerability management integration on AWS EC2 instance for cloud environements.
Prerequisites:
1. You have an elastic stack **deployed in the cloud** that includes Kibana, elasticsearch and fleet-server
2. You have AWS CLI installed on your laptop and configured to work with our dev account `elastic-security-cloud-security-dev`

Steps:
1. Install Vulnerability Management integration on a new agent policy, you might have to check the "Display beta integrations" checkbox.
2. After you installed the integration you can install a new elastic-agent, you should keep the fleet URL and the enrollment token.
3. The installation is done using a bash script that provisions our CloudFormation template.
The script accepts 3 parameters:
STACK_NAME - every CloudFormation stack should have a unique name
FLEET_URL - of your environment
ENROLLMENT_TOKEN - of your agent policy
From cloudbeat repository run:
`DEV=1 ./deploy/cloudformation/create-stack.sh <STACK_NAME> <FLEET_URL> <ENROLLMENT_TOKEN>`
The `DEV=1` environment variable will use a dev CloudFormation template that will download `elastic-agent-8.8.0-SNAPSHOT` from https://snapshots.elastic.co instead of https://artifacts.elastic.co where it still not exist.
4. The script will create a CloudFormation stack and you can track its progress on https://console.aws.amazon.com/cloudformation/
5. Once it's completed, an elastic-agent process will immediately start on the EC2 instance, and you should be able to see it on your agents screen.

**Comment by kfirpeled** [comment]
@amirbenun it would be nice if we could have a one-liner for running cloudbeat locally

1. It will be kept maintained and I don't need to worry about my local configuration get out of sync
2. Simplifies the process

**Comment by tehilashn** [comment]
Since we have something basic, moving the priority from 0 to 1
