### ISSUE TITLE
Populate vulnerability.reference with a link to NVD rather then aquasec domain

### ISSUE THREAD

**Issue by amirbenun** [elastic/cloudbeat#869]
**Motivation**
`vulnerability.reference` field should point to a website with documentation about the vulnerability.
Today, cloudbeat takes the link from the trivy's field, and that link points to `aquasec` domain.
Instead, we want to replace the link with a link of the form `nvd.nist.gov/vuln/detail/VULNERABILITY_ID` as discussed [here](https://github.com/elastic/kibana/issues/150505#issuecomment-1495600543). 

**Definition of done**
What needs to be completed at the end of this task
- [ ] Compose a new link and populate `vulnerability.reference` before sending to ES.

**Related tasks/epics**
- https://github.com/elastic/kibana/issues/150505

**Comment by kfirpeled** [comment]
Assigned to max as a good first issue on cloudbeat, moved team to Cloud Risk
cc: @oren-zohar

**Comment by maxcold** [comment]
Hey @amirbenun and @kfirpeled , I created a PR to cloudbeat https://github.com/elastic/cloudbeat/pull/1303 to generate `vulnerability.reference` using the same logic as we have in Kibana to generate a link to vulnerability to NVD site. I plan to remove the logic from the frontent and use the `vulnerability.reference` directly. I want to bring up a couple of small concerns related to this change to validate that I should proceed with the change:
1. removing the logic from the frontend means that with the new version of Kibana and with the old data the link will be pointing to `aquasec`. In my opinion this is acceptable taking into account that the only reason I see for this change is to simplify the logic on the frontend.  Do you agree?
2. by having this logic in cloudbeat there is a very small risk that for some users it might be unintended breaking change if they for some reason relied on the `reference` being aquasec before and it changes to nvd (eg. for some automation, but tbh I doubt that we already have such users). An alternative would be to introduce a new field smth like `nvdReference` or smth, but I feel that it would be overcomplication
3. while working on the feature I had a question why do we replace aquasec links with nvd ones in the first place? having this logic in my opinion just adds complexity as we can't always guarantee that the vulnerability is in NVD database and relying on a bit inderect logic of checking "if CVSS contains nvd we guess that it's safe to compose an nvd link out of vuln id". Not a big deal or smth, just wondering why having aquasec links are not suitable for us.

**Comment by maxcold** [comment]
I found a discussion regarding point 3 https://github.com/elastic/security-team/issues/5548#issuecomment-1375744828 , with the product requirements around that. I guess this answers my question, but I also not sure if we should shy away from exposing the link to aqua as we are using the tools they built :)

**Comment by kfirpeled** [comment]
@maxcold I think it would be ok to have more than one reference on the vulnerability
Not necessary to switch between the two

This will allow us flexibility with any future requirements

As for the fields I would suggest the following

```
db: {
  nvd: {
    reference: "url"
  }
} 
```

with the same thought of enabling any future enhancements

**Comment by maxcold** [comment]
@kfirpeled as discussed (I hope I captured it correctly) we continue with the original DoD on the ticket - replacing the Aqua link with NVD link on the `vulnerability.reference`. Introducing a new structure on vulnerability in my opinion requires more planning and alignment with the product because my understanding was that we want to get rid of Aqua links from the vulnerability document completely. The "breaking change" risk is very small as far as I can assess, so removing the logic from the FE also shouldn't be an issue. In the end, we are not changing the schema of the document, only the content of the `reference` attribute

**Comment by kfirpeled** [comment]
Yep, thank you for bringing this up. 
I'm ok with both options with how to handle it on the FE side - your call

As for introducing a more robust way to include the information - I agree with you as well. Lets not move forward with it atm.

**Comment by moukoublen** [comment]
@maxcold If the  field `vulnerability.cvss.nvd.V3Vector` is missing, the reference falls back to aquasec (which aligns from the code in PR). 

I would just like to confirm that this is the expected/wanted behaviour in order to consider this verified. 

Thanks ☺️ 

<img width="2387" alt="Screenshot 2023-10-23 at 2 19 09 PM" src="https://github.com/elastic/cloudbeat/assets/1380039/b4143ed8-d7ec-4163-ba24-cd7ba3ecfdf3">

**Comment by maxcold** [comment]
@moukoublen thanks for testing this! yes, this is the expected behavior
