### ISSUE TITLE
[Design] org account support for CIS AWS

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#982]
**Summary**
[AWS Organizations](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_introduction.html), a service provided by Amazon Web Services (AWS), empowers users to consolidate multiple AWS accounts into a single "organization" within AWS for seamless management. This service is invaluable for users with multiple accounts, especially large enterprises, as it streamlines billing, security (visibility), and compliance across numerous AWS accounts.

However, our current onboarding process for CSPM presents a challenge for these users; users must set up access and deploy an agent for each account individually, which is both time-consuming and a significant barrier to adoption at scale. For instance, a customer with 196 AWS accounts would need to create IAM roles in each account and deploy 196 agents in order to adopt CSPM (this is the scenario our InfoSec team faces). This cumbersome process hinders customers with multiple accounts from leveraging our features.

This epic aims to enhance the current onboarding experience by allowing users to onboard all their AWS accounts by leveraging AWS Organizations. This will enable users to adopt these features at scale rapidly.

**Prerequisites**
- [ ] Org account, few options:
  - Ask IT for a new account
  - Use InfoSec's account
  - Create a personal account 

**Open Questions**
- [x] Is it possible to audit multiple accounts using AWS SDK / API
- [x] Is there an AWS account-specific config file?

**Defenition of done**
- [ ] Cloudbeat supporting single-account audit
- [ ] CloudFormation to create Organization-wide roles
- [ ] Propose possible solutions, and choose the best one 
- [ ] How to group the resources on different accounts under one org, and how to avoid dupes

**Points of emphasis**
- Scale - How will the proposed solution affect Cloudbeat performance, will it be able to audit multiple accounts in one cycle?
- Codebase - How will the proposed change affect our code base, will it means we'll need to refactor all of our fetchers for example?
- API call limit

**Related Tasks**
- https://github.com/elastic/security-team/issues/6331

**Refs**
- https://docs.aws.amazon.com/config/latest/APIReference/API_ListAggregateDiscoveredResources.html
- https://docs.aws.amazon.com/organizations/latest/userguide/orgs_permissions_iam-policies.html
- https://docs.aws.amazon.com/organizations/index.html
- https://docs.aws.amazon.com/cli/latest/reference/organizations/list-accounts.html
- https://docs.aws.amazon.com/config/latest/developerguide/aggregate-data.html

**Comment by orestisfl** [comment]
# Proposed approach: StackSet with IAM Roles per organization account + AssumeRole

Overview: Leverage [AWS CloudFormation StackSets](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/what-is-cfnstacksets.html) to create appropriate IAM roles in each member account. Cloudbeat will then use the [`AssumeRole`](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html) API to access resources across different accounts.

![diagram](https://github.com/elastic/cloudbeat/assets/5778622/804078d9-b243-44eb-8e8a-c7acc69d0cbf)

## Set-up Process

### Requirements

1. [Full-featured](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_org_support-all-features.html) AWS Organization
2. Access to the [management account](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_getting-started_concepts.html) or [delegated administrator permissions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-orgs-delegated-admin.html).
> In addition to your organization's management account, member accounts with delegated administrator permissions can create and manage stack sets with service-managed permissions for the organization. Stack sets with service-managed permissions are created in the management account, including stack sets created by delegated administrators.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-orgs-delegated-admin.html
3. [Trusted access with AWS Organizations](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-orgs-enable-trusted-access.html) (for service-managed permissions)

### User Actions

1. User selects the "AWS Organization" option in the CSPM integration setup
2. In the Add Agent flyout, the user clicks on a CloudFormation quick-create link which opens in their AWS console
3. The CloudFormation template parameters allow the selection of either organization units (can be the root one) or a list of accounts

## CloudFormation Stack

The CloudFormation creates these resources:
1. A `cloudbeat-root` IAM role in the management account. Its policy allows access to the [Organizations API](https://docs.aws.amazon.com/organizations/latest/APIReference/Welcome.html) and the [`AssumeRole` API](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html). This is the role that cloudbeat will use to fetch resources from other member accounts. In addition, it has the usual `SecurityAudit` policy attached which will allow fetching resources in the management account.
2. StackSets across all selected accounts which create `cloudbeat-securityaudit` IAM roles in each one of them. These have the `SecurityAudit` policy attached that allows fetching resources in those accounts.
  - The StackSet will use [service-managed](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-concepts.html#stacksets-concepts-stackset-permission-models) permissions which means that when new accounts are added to the organization, resources will be created on them automatically.
3. Everything else that is created with our current CloudFormation for the single-account CSPM integration. Specifically, an EC2 instance in the management account which runs elastic-agent and cloudbeat. Cloudbeat needs to be deployed in the management AWS account because that's where the `cloudbeat-root` IAM role is located.


### Alternatives

- The account holding the `cloudbeat-root` is configurable, this configuration needs to be shared in the cloudbeat config and the CloudFormation template.
- The account holding the EC2 instance that runs cloudbeat is configurable, this will require similar configuration as the point above.

## Cloudbeat changes

A new boolean is added to the cloudbeat config that enables multi-account mode. No further configuration is needed as we'll start scanning our organization recursively.

In multi-account mode cloudbeat will:
1. Assume the `cloudbeat-root` role, if that step fails it's an unrecoverable error.
2. Scan recursively the organization using the [`ListAccounts` API](https://docs.aws.amazon.com/organizations/latest/APIReference/API_ListAccounts.html) to discover all member accounts
3. For each account, assume the `arn:aws:iam::<account-id>:role/cloudbeat-securityaudit` role
  - If we run in permission errors in specific accounts (e.g. role is missing), we ignore them and proceed. That's okay because permissions might not have been given in all accounts.
4. For each account, launch all fetchers using the assumed role

## Codebase impact

I don't think the fetchers code needs to be modified at all, except for credential handling:
Credentials need to be loaded using the [`AssumeRoleProvider`](https://github.com/aws/aws-sdk-go/blob/v1.44.273/aws/credentials/stscreds/assume_role_provider.go#L139-L248) from the AWS SDK. However, [`GetAWSCredentials`](https://github.com/elastic/beats/blob/c64f433f995106aabc28292eaee1590e3c53989e/x-pack/libbeat/common/aws/credentials.go#L86-L98) in libbeat doesn't support that out of the box. We need to either modify the library to support it or manually edit the returned aws config for each fetcher initialization.

**Comment by eyalkraft** [comment]
Thanks for this detailed proposal @orestisfl ! Seems like a great proposal.

> The StackSet will use [service-managed](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-concepts.html#stacksets-concepts-stackset-permission-models) permissions which means that when new accounts are added to the organization, resources will be created on them automatically.

Awesome!

regarding

> If we run in permission errors in specific accounts (e.g. role is missing), we ignore them and proceed. That's okay because permissions might not have been given in all accounts.

Will we have a way to determine if the account that assumeRole is failing for was intentionally left out by the customer, or for some reason isn't monitored as a result of an error? The bad scenario here is if we leave some accounts unmonitored even though our customers expect them to be monitored.

Maybe we need a way to tell our costumers that we know about these accounts, and that they're unmonitored.
@tinnytintin10 

 Also two points from @oren-zohar that weren't answered:
 

> - Scale - How will the proposed solution affect Cloudbeat performance, will it be able to audit multiple accounts in one cycle?

> - API call limit

**Comment by tommyers-elastic** [comment]
> Credentials need to be loaded using the [AssumeRoleProvider](https://github.com/aws/aws-sdk-go/blob/v1.44.273/aws/credentials/stscreds/assume_role_provider.go#L139-L248) from the AWS SDK. However, [GetAWSCredentials](https://github.com/elastic/beats/blob/c64f433f995106aabc28292eaee1590e3c53989e/x-pack/libbeat/common/aws/credentials.go#L86-L98) in libbeat doesn't support that out of the box. We need to either modify the library to support it or manually edit the returned aws config for each fetcher initialization.

hey @eyalkraft - this functionality sounds super useful for onboarding observability customers on AWS too. making the functionality available via libbeat as opposed to something manual in cloudbeat would be greatly preferred to allow us to make use of this too. please include @elastic/obs-cloud-monitoring in any PRs on these libbeat code paths.

**Comment by tinnytintin10** [comment]
@orestisfl, thank you for the great overview! It aligns perfectly with the [requirements of the epic](https://github.com/elastic/security-team/issues/6331) 👌

The only question at the moment: apart from the expenses associated with deploying and running the EC2 instance, which will be borne by the customer, are we aware of any additional costs that the customer might incur from the cloud provider due to this approach? If that’s the case, lmk; we need to make sure to document this clearly.

Additionally, one important aspects to consider: handling API Rate Limits: Given the potential scale of an AWS Organization and the number of involved accounts, Cloudbeat could encounter API rate limits due to the frequent AssumeRole API calls necessary for scanning the accounts. It will be good to have mechanisms for dealing with API throttling or rate limits. Engaging our internal cloud security team for preliminary alpha testing could be invaluable in identifying any potential bottlenecks. When this is ready for testing, let's be sure to engage them (can make the introduction if necessary).

**Comment by orestisfl** [comment]
> 2. Access to the [management account](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_getting-started_concepts.html) or [delegated administrator permissions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-orgs-delegated-admin.html).

Regarding the delegated admin part:

It's possible to create the CloudFormation stack using a different account than the management account of the organization.

However, this will create both an `cloudbeat-root` and `cloudbeat-securityaudit` role in the delegated admin account and will not create a role at all in the management account. This means that cloudbeat will **not** have a way to scan resources in the management account leaving a security hole that might not be obvious immediately to the user. I propose to not provide this option (it wasn't part of the epic, just a nice-to-have).

Only source I found for this is a reddit post: https://www.reddit.com/r/aws/comments/u1b78n/stackset_not_deploying_to_management_account/

**Comment by orestisfl** [comment]
Discussion still welcome but I don't see the reason to keep this as open
